common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
app_name = 'common'

urlpatterns = [
    path('login/',auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(),name='logout'),
    path('signup/', views.signup, name='signup'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('common/', include('common.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('main.urls')),
    
]
handler404 = 'common.views.page_not_found'

main/urls.py
from django.contrib import admin
from django.urls import path,include
from main.views import index, blog, posting, new_post, remove_post, post_modify
# 이미지 업로드
from django.conf.urls.static import static
from django.conf import settings

app_name = "main"

urlpatterns = [
    path('', index, name='index'),
    path('blog/', blog, name='blog'),
    path('blog/<int:pk>/',posting,name='posting'),
    path('blog/new_post/', new_post, name='new_post'),
    path('blog/<int:pk>/remove/',remove_post, name='remove_post'),
    path('blog/modify/<int:pk>/', post_modify, name='post_modify'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

common/models.py
from django.db import models

# Create your models here.

main/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Post(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    modify_date = models.DateTimeField(null=True, blank=True)
    postname = models.CharField(max_length=200)
    mainphoto = models.ImageField(blank=True, null=True)
    contents = models.TextField()
    create_date = models.DateTimeField()
    # postname이 Post object 대신 나오게 함
    def __str__(self):
        return self.postname

common/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class UserForm(UserCreationForm):
    email = forms.EmailField(label="이메일")

    class Meta:
        model = User
        fields = ("username", "password1", "password2", "email")

common/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from common.forms import UserForm
# Create your views here.

def signup(request):
    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(usename=username, password=raw_password)
            user = form.save()
            login(request, user)
            return redirect('main:index')
    else:
        form = UserForm()
    return render(request, 'common/signup.html', {'form' : form })

def page_not_found(request, exception):
    return render(request, 'common/404.html', {})

main/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.utils import timezone
from main.models import Post
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from django.contrib import messages
# Create your views here.

def index(request):
    return render(request, 'main/index.html')
def blog(request):
    postlist = Post.objects.order_by('-create_date')
    page = request.GET.get('page','1')
    paginator = Paginator(postlist, 10)
    page_obj = paginator.get_page(page)
    # blog.html을 열 때 postlist도 같이 가져온다
    return render(request, 'main/blog.html', { 'postlist' : page_obj})
def posting(request, pk):
    # 게시글(Post) 중 pk를 이용해 하나의 게시글(post)를 검색
    post = get_object_or_404(Post, pk=pk)
    # posting.html 페이지를 열 때, 찾아낸 게시글(post)를 post라는 이름으로 가져옴
    return render(request, 'main/posting.html',{ 'post' : post })
@login_required(login_url='common:login')
def new_post(request):
    if request.method == "POST":
        if request.POST['mainphoto']:
            new_article=Post.objects.create(
                author=request.user,
                postname=request.POST['postname'],
                contents=request.POST['contents'],
                mainphoto=request.POST['mainphoto'],
                create_date= timezone.now(),
            )
        else:
            new_article=Post.objects.create(
                author=request.user,
                postname=request.POST['postname'],
                contents=request.POST['contents'],
                mainphoto='',
                create_date=timezone.now(),
            )
        return redirect('/blog/')
    return render(request, 'main/new_post.html')
def remove_post(request, pk):
    post = Post.objects.get(pk=pk)
    if request.method == "POST":
        post.delete()
        return redirect('/blog')
    return render(request, 'main/remove_post.html',{'Post' : post})
@login_required
def post_modify(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.user != post.author:
        messages.error(request, 'Permission denied')
        return redirect('main:posting',pk=pk)
    if request.method == "POST":
        post.author=request.user
        post.postname=request.POST['postname']
        post.contents=request.POST['contents']
        post.mainphoto=request.POST['mainphoto']
        post.create_date=timezone.now()
        post.save()
        return redirect('/blog/'+str(pk),{'post' : post})
    return render(request, 'main/new_post.html')

main/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <title>Document</title>
</head>
<body>
    <!-- 네비게이션 -->
    {% include "navbar.html" %}
    {% block content %}
    {% endblock %}
    <script src="{% static 'bootstrap.min.js' %}"></script>
</body>
</html>

main/templates/common/login.html
{% extends "base.html" %}
{% block content %}
<div class="container my-3">
    <form method="post" action="{% url 'common:login' %}">
        {% csrf_token %}
        <input type="hidden" name="next" value="{{ next }}">
        {% include "form_error.html" %}
        <div class="mb-3">
            <label for="username">사용자ID</label>
            <input type="text" class="form-control" name="username" id="username" value="{{ form.username.value|default_if_none:''}}">
        </div>
        <div class="mb-3">
            <label for="password">비밀번호</label>
            <input type="password" class="form-control" name="password" id="password" value="{{ form.password.value|default_if_none:''}}">
        </div>
        <button type="submit" class="btn btn-primary">로그인</button>
    </form>
</div>
{% endblock %}

main/templates/common/signup.html
{% extends  "base.html" %}
{% block content %}
<div class="container my-3">
    <form method="post" action="{% url 'common:signup' %}">
        {% csrf_token %}
        {% include "form_error.html" %}
        <div class="mb-3">
            <label for="username">사용자 이름</label>
            <input type="text" class="form-control" name="username" id="username"
                value="{{ form.username.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="password1">Password</label>
            <input type="password" class="form-control" name="password1" id="password1"
                value="{{ form.password1.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="password2">Verify Password</label>
            <input type="password" class="form-control" name="password2" id="password2"
                value="{{ form.password2.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="email">Email</label>
            <input type="text" class="form-control" name="email" id="email"
                value="{{ form.email.value|default_if_none:'' }}">
        </div>
        <button type="submit" class="btn btn-primary">생성하기</button>
    </form>
</div>
{% endblock %}

main/templates/form_error.html
{% if form.errors %}
<div class="alert alert-danger">
    {% for field in form %}
    <!--필드오류-->
    {% if field.errors %}
    <div>
        <strong>{{ field.label }}</strong>
        {{ field.errors }}
    </div>
    {% endif %}
    {% endfor %}
    <!--non 필드오류-->
    {% for error in form.non_field_errors %}
    <div>
        <strong>{{ error }}</strong>
    </div>
    {% endfor %}
</div>
{% endif %}

main/templates/main/blog.html
{% extends 'base.html' %}
{% load main_filter %}
{% block content %}
<div class="container my-3">
    <table class="table">
        <thead>
            <tr class="table-dark">
                <th>번호</th>
                <th>제목</th>
                <th>작성일시</th>
                <th>글쓴이</th>
            </tr>
        </thead>
    <tbody>
        {% if postlist %}
        {% for list in postlist %}
        <tr>
            <td>
                <!--번호 = 전체 건수 - 시작 인덱스 - 현재 인덱스 +1 -->
                {{ postlist.paginator.count|sub:postlist.start_index|sub:forloop.counter0|add:1 }}
            </td>
            <td>
                <a href="{% url 'main:posting' list.pk %}">{{ list.postname }}</a>
            </td>
            <td>
                {{ list.create_date }}
            </td>
            <td>
                {{ list.author }}
            </td>
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td colspan="3">게시글이 없습니다.</td>
        </tr>
        {% endif %}
    </tbody>
</table>
    <ul class="pagination justify-content-center">
        <!-- 이전 -->
        {% if postlist.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page{{ postliat.previous_page_number }}">이전</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
        </li>
        {% endif %}
        <!--페이지 리스트-->
        {% for page_number in postlist.paginator.page_range %}
        {% if page_number >= postlist.number|add:-5 and page_number <= postlist.number|add:5 %}
        {% if page_number == postlist.number %}
        <li class="page-item active" aria-current="page">
            <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
        </li>
        {% else %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
        </li>
        {% endif %}
        {% endif %}
        {% endfor %}
        <!--다음 페이지-->
        {% if postlist.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ postlist.next_page_number }}">다음</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1"  aria-disabled="true" href="#">다음</a>
        </li>
        {% endif %}
    </ul>
    <!--페이징 처리-->
    <div class="my-3 border-bottom pb-2">
        <button type="button" class="btn btn-primary btn-lg btn-block" onclick="location.href='new_post/'">
            글 쓰기
        </button>
    </div>
</div>
{% endblock %}

main/templates/main/index.html
{% extends 'base.html' %}

main/templates/main/new_post.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>글쓰기 페이지</title>
</head>
<body>
    <h1>글쓰기 페이지</h1>
    <form method="post">
        {% csrf_token %}
        제목<br>
        <input type="text" name="postname"><br>
        내용<br>
        <textarea rows="10" cols="50" name="contents"></textarea><br>
        <input type="file" name="mainphoto"><br>
        <input type="submit" name="글쓰기">
    </form>
</body>
</html>

main/templates/main/posting.html
<html>
    <head>
        <title>Posting!</title>
    </head>
    <body>
        <h1>게시글 개별 페이지</h1>
        <p>{{ post.postname }}</p>
        <p>{{ post.contents }}</p>
        <!-- 이미지 -->
        {% if post.mainphoto %}
            <img src="{{ post.mainphoto }}" alt="" height="600">
            <br>
        {% endif %} 
        <a href="/blog/">목록</a>
        {% if request.user == post.author %}
        <a href="{% url 'main:post_modify' post.pk %}" class="btn btn-sm btn-outline-secondary">수정</a>
        <a href="/blog/{{post.pk}}/remove">삭제</a>
        {% endif %}
    </body>
</html>

main/templates/main/remove_post.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>글 삭제</title>
</head>
<body>
    <form method="POST">
        {% csrf_token %}
        <h3>{{ Post.postname }} - 삭제하기</h3>
        <button>삭제</button>
    </form>
</body>
</html>

main/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'main:index' %}">Home</a>
        <button class="navbar-toggler" type="button"
            data-bs-toggle="collapse"
            data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent"
            aria-expanded="false"
            aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    {% if user.is_authenticated %}
                    <a class="nav-link" href="{% url 'common:logout' %}">{{ user.username }} (로그아웃)</a>
                    {% else %}
                    <a class="nav-link" href="{% url 'common:login' %}">로그인</a>
                    {% endif %}
                </li>
                <li>
                    {% if not user.is_authenticated %}
                    <a class="nav-link" href="{% url 'common:signup' %}">회원가입</a>
                    <a class="nav-link" href="{% url 'password_reset' %}"> 비밀번호 찾기</a>
                    {% endif %}
                </li>
                <li>
                    <a class="nav-link" href="{% url 'main:blog' %}">게시판</a>
                </li>
            </ul>
        </div>
    </div>
</nav>